version: '3'

services:
  frontend:
    image: ryanhejs/recipe-app-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  backend:
    image: ryanhejs/recipe-app-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: recipe_app
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
